version: '3.10'
services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${DB_USER_NAME}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_HOST=${DB_HOST}
    ports:
      - ${DB_PORT}:${DB_PORT}
    env_file:
      - .env

  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${DJANGO_PORT}:${DJANGO_PORT}
    env-file:
      - .env
    depends_on:
      - db
